### ISSUE TITLE
Error: Returned error: The method eth_sendTransaction does not exist/is not available

### ISSUE THREAD

**Issue by laman-git** [ProofSuite/OrFeed#63]
Hello, 
I am trying to follow along with the tutorial series. I am on the basicArbExample task
I got close to the end of the tutorial but am getting an error when running `npm start`

Below is the following error. 
I have a good Google but sadly do not understand how to fix it.. any hints?

```
259123062128140717028
checking to see if we should execute for arb
starting arb trade. Cant execute another trade for 45 seconds
Error: Returned error: The method eth_sendTransaction does not exist/is not available
    at Object.ErrorResponse (/Users/user/Documents/Bots/DeFi App/nodetradebot/basicArbExample /node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/user/Documents/Bots/DeFi App/nodetradebot/basicArbExample /node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/user/Documents/Bots/DeFi App/nodetradebot/basicArbExample /node_modules/web3-providers-http/src/index.js:110:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/user/Documents/Bots/DeFi App/nodetradebot/basicArbExample /node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/user/Documents/Bots/DeFi App/nodetradebot/basicArbExample /node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/user/Documents/Bots/DeFi App/nodetradebot/basicArbExample /node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/user/Documents/Bots/DeFi App/nodetradebot/basicArbExample /node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
undefined
Uniswap SAI Buy price is:
260986259497302810725
Kyber SAI Sell price is:

```

**Comment by mikedeshazer** [comment]
@laman-git make sure to do an npm install before npm start.
